#!/bin/bash

set -x

BASE=$(readlink -f $(dirname $0))

PBF=~/projects/osm/pbfdata/region/kreisgt/kreis-guetersloh.osm.pbf

OUTFILE=${BASE}/sqlite-output/alkis-gebaeude-diff.$(date +%Y%m%d%H%M).sqlite
ALKISDUMP=$(ls -1t ${BASE}/alkis-nas-dump/*.sql | head -1)

time docker run -i --rm \
	-v ${BASE}:/current \
	-v $(dirname ${PBF}):/pbf \
	-v $(dirname ${OUTFILE}):/output \
	-v $(dirname ${ALKISDUMP}):/alkis \
	-e PBFFILE=/pbf/$(basename ${PBF}) \
	-e ALKISFILE=/alkis/$(basename ${ALKISDUMP}) \
	-e OUTFILE=/output/$(basename ${OUTFILE}) \
	flo/postgis \
	/current/process-diff-alkis-osm

set -e

sqlite3 ${OUTFILE} <alkisdiff-meta.sql
sqlite3 ${OUTFILE} "update buildingnotinosm set style='green' where area < alkisarea*0.1;"
sqlite3 ${OUTFILE} "update buildingnotinosm set style='red' where area > alkisarea*0.9;"
sqlite3 ${OUTFILE} "update buildingnotinosm set style='yellow' where area between alkisarea*0.1 and alkisarea*0.9;"

sqlite3 ${OUTFILE} "update waternotinosm set style='green' where area < alkisarea*0.1;"
sqlite3 ${OUTFILE} "update waternotinosm set style='red' where area > alkisarea*0.9;"
sqlite3 ${OUTFILE} "update waternotinosm set style='yellow' where area between alkisarea*0.1 and alkisarea*0.9;"

cp ${OUTFILE} /var/www/osm.zz.de/spatialite-rest/databases/alkisdiff.sqlite

rm ${OUTFILE}
